/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "asd.check" instead.
 */

#include <check.h>

#line 1 "asd.check"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>

#include "s21_decimal.h"
#include "decimal_core.h"

float Rand_R(float a, float b) {
  srand(time(NULL));
  float m = (float)rand() / RAND_MAX;
  float num = a + m * (b - a);
  return num;
}


START_TEST(isequal__not_equal)
{
#line 20
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_equal(a, b), 0);

}
END_TEST

START_TEST(isequal__equal)
{
#line 25
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_equal(b, b), s21_is_equal(a, b));

}
END_TEST

START_TEST(isequal__different_exp)
{
#line 30
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
set_exp(&b, 10);
ck_assert_int_eq(s21_is_equal(b, a), 0);

}
END_TEST

START_TEST(isnot_equal__not_equal)
{
#line 38
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{-9,0,9,0}};
ck_assert_int_eq(s21_is_not_equal(a, b), 1);

}
END_TEST

START_TEST(isnot_equal__equal)
{
#line 43
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_not_equal(b, b), s21_is_not_equal(a, b));

}
END_TEST

START_TEST(isnot_equal__different_exp)
{
#line 48
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
set_exp(&b, 10);
ck_assert_int_eq(s21_is_not_equal(b, a), 1);

}
END_TEST

START_TEST(isnot_equal__auto_generate)
{
#line 54
s21_decimal a = {{297293388, 544714707, 329431639, 0}};
chang_sign(&a);
s21_decimal b = {{1344688107, 485745822, 1475553454, 0}};
ck_assert_int_ne(s21_is_equal(a, b), s21_is_equal(b, b));

}
END_TEST

START_TEST(isnot_equal__auto)
{
#line 60
s21_decimal a = {{1135069503, 1879099755, 333599775, 0}};
s21_decimal b = {{629715255, 1134024340, 1746726690, 0}};
chang_sign(&b);
ck_assert_int_eq(s21_is_not_equal(a, b), s21_is_equal(b, b));

}
END_TEST

START_TEST(isgreater__sign)
{
#line 68
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{-9,0,9,0}};
chang_sign(&a);
chang_sign(&b);
ck_assert_int_eq(s21_is_greater(a, b), 1);

}
END_TEST

START_TEST(isgreater__1)
{
#line 75
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{-9,0,9,0}};
ck_assert_int_eq(s21_is_greater(a, b), 0);

}
END_TEST

START_TEST(isgreater__12)
{
#line 80
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&b);
ck_assert_int_eq(s21_is_greater(a, b), 1);

}
END_TEST

START_TEST(isgreater__13)
{
#line 86
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_greater(a, b), 0);

}
END_TEST

START_TEST(isgreater__14)
{
#line 91
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_greater(b, a), 1);

}
END_TEST

START_TEST(isgreater__15)
{
#line 96
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_greater(b, a), 0);

}
END_TEST

START_TEST(isgreater__16)
{
#line 101
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&a);
chang_sign(&b);
ck_assert_int_eq(s21_is_greater(b, a), 0);

}
END_TEST

START_TEST(isgreater__17)
{
#line 108
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&a);
ck_assert_int_eq(s21_is_greater(a, b), 0);

}
END_TEST

START_TEST(isgreater__18)
{
#line 114
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&b);
ck_assert_int_eq(s21_is_greater(a, b), 1);

}
END_TEST

START_TEST(isgreater__0)
{
#line 120
s21_decimal a = {{0, 0, 0, 0}};
s21_decimal b = {{-9, 0, 9, 0}};
ck_assert_int_eq(s21_is_greater(a, b), 0);

}
END_TEST

START_TEST(isgreater__02)
{
#line 125
s21_decimal a = {{0, 0, 0, 0}};
s21_decimal b = {{9, 0, 9, 0}};
ck_assert_int_eq(s21_is_greater(a, b), 0);

}
END_TEST

START_TEST(isgreater_or_equal__11)
{
#line 130
s21_decimal a = {{0, 0, 0, 0}};
s21_decimal b = {{0, 0, 0, 0}};
ck_assert_int_eq(s21_is_greater_or_equal(a, b), 1);

}
END_TEST

START_TEST(isgreater_or_equal__12)
{
#line 135
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&b);
ck_assert_int_eq(s21_is_greater_or_equal(a, b), 1);

}
END_TEST

START_TEST(isgreater_or_equal__13)
{
#line 141
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_greater_or_equal(a, b), 0);

}
END_TEST

START_TEST(isgreater_or_equal__14)
{
#line 146
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_greater_or_equal(b, a), 1);

}
END_TEST

START_TEST(isgreater_or_equal__15)
{
#line 151
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_greater_or_equal(b, a), 1);

}
END_TEST

START_TEST(isgreater_or_equal__16)
{
#line 156
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&a);
chang_sign(&b);
ck_assert_int_eq(s21_is_greater_or_equal(b, a), 1);

}
END_TEST

START_TEST(isgreater_or_equal__17)
{
#line 163
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&a);
ck_assert_int_eq(s21_is_greater_or_equal(a, b), 0);

}
END_TEST

START_TEST(isgreater_or_equal__18)
{
#line 169
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&b);
ck_assert_int_eq(s21_is_greater_or_equal(a, b), 1);

}
END_TEST

START_TEST(isgreater_or_equal__19)
{
#line 175
s21_decimal a = {{-9, -9, -1, 0}};
s21_decimal b = {{0, 2, 54, 0}};
ck_assert_int_eq(s21_is_greater_or_equal(a, b), 1);

}
END_TEST

START_TEST(isgreater_or_equal_sign)
{
#line 180
s21_decimal a = {{-9, -9, -1, 0}};
s21_decimal b = {{0, 2, 54, 0}};
chang_sign(&a);
chang_sign(&b);
ck_assert_int_eq(s21_is_greater_or_equal(a, b), 0);

}
END_TEST

START_TEST(isgreater_or_equal__0)
{
#line 187
s21_decimal a = {{-9, 0, 0, 0}};
s21_decimal b = {{0, 5, 8, 0}};
ck_assert_int_eq(s21_is_greater_or_equal(a, b), 0);

}
END_TEST

START_TEST(isgreater_or_equal__auto)
{
#line 192
s21_decimal a = {{210613260, 85365008, 330809813, 0}};
s21_decimal b = {{1039012127, 388364480, 803205246, 0}};
ck_assert_int_ne(s21_is_greater_or_equal(a, b), s21_is_greater_or_equal(b, a));

}
END_TEST

START_TEST(isgreater_or_equal__20)
{
#line 197
float num1 = 1.375323;
float num2 = 1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(isgreater_or_equal__21)
{
#line 206
int num1 = 2;
int num2 = 1;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(isgreater_or_equal__22)
{
#line 215
float num1 = 1.39;
float num2 = -1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(isgreater_or_equal__23)
{
#line 224
int num1 = 0;
int num2 = 0;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(isgreater_or_equal__24)
{
#line 233
int num1 = 3;
int num2 = 9;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(isgreater_or_equal__25)
{
#line 242
int num1 = -3;
int num2 = -3;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(isgreater_or_equal__26)
{
#line 251
int num1 = 10;
int num2 = 3;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(isgreater_or_equal__27)
{
#line 260
float num1 = 10423546.34534534;
float num2 = 3.34534534;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(isgreater_or_equal__28)
{
#line 269
float num1 = -3.34534534;
float num2 = 3.34534534;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(isgreater_or_equal__29)
{
#line 278
float num1 = 1042634.34534534;
float num2 = 10424546.34534534;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(isgreater_or_equal__30)
{
#line 287
float num1 = 10426.34534534;
float num2 = 104234.345345;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(isgreater_or_equal__31)
{
#line 296
float num1 = 1042.5667777;
float num2 = 1042.345345;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_greater_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(isgreater_or_equal__32)
{
#line 305
s21_decimal dec5 = {
    {12345, 0, 0, 0b00000000000001000000000000000000}};  //  1.2345
s21_decimal dec6 = {{12, 0, 0, 0b10000000000000010000000000000000}};  //
ck_assert_int_eq(s21_is_greater_or_equal(dec5, dec6), 1);
ck_assert_int_eq(s21_is_greater_or_equal(dec6, dec5), 0);

s21_decimal dec7 = {
    {12345, 0, 0, 0b10000000000001000000000000000000}};  // -1.2345
s21_decimal dec8 = {{12, 0, 0, 0b00000000000000010000000000000000}};
ck_assert_int_eq(s21_is_greater_or_equal(dec7, dec8), 0);
ck_assert_int_eq(s21_is_greater_or_equal(dec8, dec7), 1);

s21_decimal dec1 = {
    {12345, 0, 0, 0b00000000000001000000000000000000}};  //  1.2345
s21_decimal dec2 = {{12, 0, 0, 0b00000000000000010000000000000000}};
ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 1);
ck_assert_int_eq(s21_is_greater_or_equal(dec2, dec1), 0);

s21_decimal dec3 = {
    {12345, 0, 0, 0b10000000000001000000000000000000}};  // -1.2345
s21_decimal dec4 = {{12, 0, 0, 0b10000000000000010000000000000000}};  //

ck_assert_int_eq(s21_is_greater_or_equal(dec3, dec4), 0);
ck_assert_int_eq(s21_is_greater_or_equal(dec4, dec3), 1);

s21_decimal dec9 = {{12345, 0, 0, 0}};
s21_decimal dec10 = {{12345, 0, 0, 0}};
ck_assert_int_eq(s21_is_greater_or_equal(dec9, dec10), 1);
ck_assert_int_eq(s21_is_greater_or_equal(dec10, dec9), 1);

s21_decimal dec11 = {{0, 0, 0, 0}};
s21_decimal dec12 = {{0, 0, 0, 0}};
ck_assert_int_eq(s21_is_greater_or_equal(dec11, dec12), 1);
ck_assert_int_eq(s21_is_greater_or_equal(dec12, dec11), 1);

}
END_TEST

START_TEST(greater_test_1)
{
#line 341
s21_decimal src1, src2;
src1.bits[0] = 0b01011000010000110001100100000110;
src1.bits[1] = 0b00000000011100101101011000000101;
src1.bits[2] = 0b00000000000000000000000000000000;
src1.bits[3] = 0b00000000000000000000000000000000;
src2.bits[0] = 0b10111110000100011000010110010111;
src2.bits[1] = 0b11011001001111010001001011000110;
src2.bits[2] = 0b00000000000001011001011001001000;
src2.bits[3] = 0b00000000000100010000000000000000;
int result = s21_is_greater(src1, src2);
int origin = 1;
ck_assert_int_eq(result, origin);

}
END_TEST

START_TEST(greater_test_2)
{
#line 355
s21_decimal a = {{0, 0, 0, 0}};
s21_decimal b = {{0, 0, S21_MAX_UINT, 0}};
ck_assert_int_eq(s21_is_greater(a, b), 0);

}
END_TEST

START_TEST(greater_test_3)
{
#line 360
s21_decimal dec5 = {
    {12345, 0, 0, 0b00000000000001000000000000000000}};  //  1.2345
s21_decimal dec6 = {
    {12, 0, 0, 0b10000000000000010000000000000000}};  //  -1.2;
ck_assert_int_eq(s21_is_greater(dec5, dec6), 1);
ck_assert_int_eq(s21_is_greater(dec6, dec5), 0);

s21_decimal dec7 = {
    {12345, 0, 0, 0b10000000000001000000000000000000}};  // -1.2345
s21_decimal dec8 = {{12, 0, 0, 0b00000000000000010000000000000000}};  //  1.2;
ck_assert_int_eq(s21_is_greater(dec7, dec8), 0);
ck_assert_int_eq(s21_is_greater(dec8, dec7), 1);

s21_decimal dec1 = {
    {12345, 0, 0, 0b00000000000001000000000000000000}};  //  1.2345
s21_decimal dec2 = {{12, 0, 0, 0b00000000000000010000000000000000}};  //  1.2
ck_assert_int_eq(s21_is_greater(dec1, dec2), 1);
ck_assert_int_eq(s21_is_greater(dec2, dec1), 0);

s21_decimal dec3 = {
    {12345, 0, 0, 0b10000000000001000000000000000000}};  // -1.2345
s21_decimal dec4 = {
    {12, 0, 0, 0b10000000000000010000000000000000}};  //   -1.2
ck_assert_int_eq(s21_is_greater(dec3, dec4), 0);
ck_assert_int_eq(s21_is_greater(dec4, dec3), 1);

}
END_TEST

START_TEST(greater_test_4)
{
#line 387
// 3856
s21_decimal src1, src2;
// src1 = 3;
// src2 = 3;

src1.bits[0] = 0b00000000000000000000000000000011;
src1.bits[1] = 0b00000000000000000000000000000000;
src1.bits[2] = 0b00000000000000000000000000000000;
src1.bits[3] = 0b00000000000000000000000000000000;
src2.bits[0] = 0b00000000000000000000000000000011;
src2.bits[1] = 0b00000000000000000000000000000000;
src2.bits[2] = 0b00000000000000000000000000000000;
src2.bits[3] = 0b00000000000000000000000000000000;
int result = s21_is_greater(src1, src2);
int origin = 0;
ck_assert_int_eq(result, origin);

}
END_TEST

START_TEST(greater_test_5)
{
#line 405
  // 3928
s21_decimal src1, src2;
// src1 = 6521;
// src2 = 74121;

src1.bits[0] = 0b00000000000000000001100101111001;
src1.bits[1] = 0b00000000000000000000000000000000;
src1.bits[2] = 0b00000000000000000000000000000000;
src1.bits[3] = 0b00000000000000000000000000000000;
src2.bits[0] = 0b00000000000000010010000110001001;
src2.bits[1] = 0b00000000000000000000000000000000;
src2.bits[2] = 0b00000000000000000000000000000000;
src2.bits[3] = 0b00000000000000000000000000000000;
int result = s21_is_greater(src1, src2);
int origin = 0;
ck_assert_int_eq(result, origin);

}
END_TEST

START_TEST(isless_or_equal__11)
{
#line 425
s21_decimal a = {{-6, -6, -6, 0}};
s21_decimal b = {{-6, -6, -6, 0}};
ck_assert_int_eq(s21_is_less_or_equal(a, b), 1);

}
END_TEST

START_TEST(isless_or_equal__12)
{
#line 430
s21_decimal a = {{-6, -6, -6, 0}};
s21_decimal b = {{-6, -6, -1, 0}};
ck_assert_int_eq(s21_is_less_or_equal(a, b), 1);

}
END_TEST

START_TEST(isless_or_equal__13)
{
#line 435
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&b);
ck_assert_int_eq(s21_is_less_or_equal(a, b), 0);

}
END_TEST

START_TEST(isless_or_equal__14)
{
#line 441
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_less_or_equal(a, b), 1);

}
END_TEST

START_TEST(isless_or_equal__15)
{
#line 446
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_less_or_equal(b, a), 0);

}
END_TEST

START_TEST(isless_or_equal__16)
{
#line 451
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_less_or_equal(b, a), 1);

}
END_TEST

START_TEST(isless_or_equal__17)
{
#line 456
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&a);
chang_sign(&b);
ck_assert_int_eq(s21_is_less_or_equal(b, a), 1);

}
END_TEST

START_TEST(isless_or_equal__18)
{
#line 463
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&a);
ck_assert_int_eq(s21_is_less_or_equal(a, b), 1);

}
END_TEST

START_TEST(isless_or_equal__19)
{
#line 469
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&b);
ck_assert_int_eq(s21_is_less_or_equal(a, b), 0);

}
END_TEST

START_TEST(isless_or_equal__110)
{
#line 475
s21_decimal a = {{-9, -9, -1, 0}};
s21_decimal b = {{0, 2, 54, 0}};
ck_assert_int_eq(s21_is_less_or_equal(a, b), 0);

}
END_TEST

START_TEST(isless_or_equal__0)
{
#line 480
s21_decimal a = {{-6, -6, -6, 0}};
s21_decimal b = {{-9, -9, -9, 0}};
ck_assert_int_eq(s21_is_less_or_equal(a, b), 0);


}
END_TEST

START_TEST(isless__1)
{
#line 486
s21_decimal a = {{0, 0, 0, 0}};
s21_decimal b = {{6, 6, 6, 0}};
ck_assert_int_eq(s21_is_less(a, b), 1);

}
END_TEST

START_TEST(isless__12)
{
#line 491
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&b);
ck_assert_int_eq(s21_is_less(a, b), 0);

}
END_TEST

START_TEST(isless__13)
{
#line 497
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_less(a, b), 1);

}
END_TEST

START_TEST(isless__14)
{
#line 502
s21_decimal a = {{0,0,0,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_less(b, a), 0);

}
END_TEST

START_TEST(isless__15)
{
#line 507
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
ck_assert_int_eq(s21_is_less(b, a), 0);

}
END_TEST

START_TEST(isless__16)
{
#line 512
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&a);
chang_sign(&b);
ck_assert_int_eq(s21_is_less(b, a), 0);

}
END_TEST

START_TEST(isless__16_1)
{
#line 519
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,10,0}};
chang_sign(&a);
chang_sign(&b);
ck_assert_int_eq(s21_is_less(b, a), 1);

}
END_TEST

START_TEST(isless__16_2)
{
#line 526
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,8,0}};
chang_sign(&a);
chang_sign(&b);
ck_assert_int_eq(s21_is_less(b, a), 0);

}
END_TEST

START_TEST(isless__17)
{
#line 533
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&a);
ck_assert_int_eq(s21_is_less(a, b), 1);

}
END_TEST

START_TEST(isless__18)
{
#line 539
s21_decimal a = {{9,0,9,0}};
s21_decimal b = {{9,0,9,0}};
chang_sign(&b);
ck_assert_int_eq(s21_is_less(a, b), 0);

}
END_TEST

START_TEST(isless__equal)
{
#line 545
s21_decimal a = {{0, 0, 0, 0}};
s21_decimal b = {{0, 0, 0, 0}};
ck_assert_int_eq(s21_is_less(a, b), 0);

}
END_TEST

START_TEST(isless__0)
{
#line 550
s21_decimal a = {{0, 0, -1, 0}};
s21_decimal b = {{6, 6, 6, 0}};
ck_assert_int_eq(s21_is_less(a, b), 0);

}
END_TEST

START_TEST(isless_1)
{
#line 555
float num1 = 1.375342323523;
float num2 = 1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(isless_2)
{
#line 564
float num1 = 1.39;
float num2 = 1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(isless_3)
{
#line 573
float num1 = 1.39;
float num2 = -1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(isless_4)
{
#line 582
int num1 = 0;
int num2 = 0;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_less(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(isless_5)
{
#line 591
int num1 = 3;
int num2 = 9;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_less(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(isless_6)
{
#line 600
int num1 = -3;
int num2 = -3;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_less(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(isless_7)
{
#line 609
float num1 = -34534534.232446543232446543;
float num2 = -3.232323233232323233;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(isless_8)
{
#line 618
s21_decimal dec5 = {
    {12345, 0, 0, 0b00000000000001000000000000000000}};  //  1.2345
s21_decimal dec6 = {{12, 0, 0, 0b10000000000000010000000000000000}};  // -1.2
ck_assert_int_eq(s21_is_less(dec5, dec6), 0);
ck_assert_int_eq(s21_is_less(dec6, dec5), 1);

s21_decimal dec7 = {
    {12345, 0, 0, 0b10000000000001000000000000000000}};  // -1.2345
s21_decimal dec8 = {{12, 0, 0, 0b00000000000000010000000000000000}};  //  1.2;
ck_assert_int_eq(s21_is_less(dec7, dec8), 1);
ck_assert_int_eq(s21_is_less(dec8, dec7), 0);

s21_decimal dec1 = {
    {12345, 0, 0, 0b00000000000001000000000000000000}};  //  1.2345
s21_decimal dec2 = {{12, 0, 0, 0b00000000000000010000000000000000}};  //  1.2;
ck_assert_int_eq(s21_is_less(dec1, dec2), 0);
ck_assert_int_eq(s21_is_less(dec2, dec1), 1);

s21_decimal dec3 = {
    {12345, 0, 0, 0b10000000000001000000000000000000}};  // -1.2345
s21_decimal dec4 = {
    {12, 0, 0, 0b10000000000000010000000000000000}};  //  -1.2;
ck_assert_int_eq(s21_is_less(dec3, dec4), 1);
ck_assert_int_eq(s21_is_less(dec4, dec3), 0);

s21_decimal dec9 = {{12345, 0, 0, 0}};
s21_decimal dec10 = {{12345, 0, 0, 0}};
ck_assert_int_eq(s21_is_less(dec9, dec10), 0);
ck_assert_int_eq(s21_is_less(dec10, dec9), 0);

s21_decimal dec11 = {{0, 0, 0, 0}};
s21_decimal dec12 = {{0, 0, 0, 0}};
ck_assert_int_eq(s21_is_less(dec11, dec12), 0);
ck_assert_int_eq(s21_is_less(dec12, dec11), 0);

}
END_TEST

START_TEST(is_less_or_equal_1)
{
#line 654
float num1 = 1.375342323523;
float num2 = 1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_2)
{
#line 663
float num1 = 1.39;
float num2 = 1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_3)
{
#line 672
float num1 = 1.39;
float num2 = -1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(is_less_or_equal_4)
{
#line 681
int num1 = 0;
int num2 = 0;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);
}
END_TEST

START_TEST(is_less_or_equal_5)
{
#line 689

int num1 = 3;
int num2 = 9;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_6)
{
#line 699
int num1 = -3;
int num2 = -3;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);
}
END_TEST

START_TEST(is_less_or_equal_7)
{
#line 707
float num1 = -3453434.232446543232446543;
float num2 = -3.232323233232323233;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);
}
END_TEST

START_TEST(is_less_or_equal_8)
{
#line 715
float num1 = -34534553434.232446543232446543;
float num2 = 34534553434.232446543232446543;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_9)
{
#line 724
float num1 = 1.78;
float num2 = 1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(is_less_or_equal_10)
{
#line 733
float num1 = -3453453452.0;
float num2 = -34.0;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_11)
{
#line 742
float num1 = 104235454634.34534534;
float num2 = 1042354546.34534534;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(is_less_or_equal_12)
{
#line 751
float num1 = 1042354546.34534534;
float num2 = 104235454634.345345;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_13)
{
#line 760
float num1 = 1042.5667777;
float num2 = 1042.345345;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(is_less_or_equal_14)
{
#line 769
float num1 = 1.375342323523;
float num2 = 1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_15)
{
#line 778
float num1 = 1.39;
float num2 = 1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_16)
{
#line 787
float num1 = 1.39;
float num2 = -1.39;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(is_less_or_equal_17)
{
#line 796
int num1 = 0;
int num2 = 0;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_18)
{
#line 805
int num1 = 3;
int num2 = 9;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_19)
{
#line 814
int num1 = -3;
int num2 = -3;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_26)
{
#line 823
int num1 = 10;
int num2 = 3;
s21_decimal dec1, dec2;
s21_from_int_to_decimal(num1, &dec1);
s21_from_int_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(is_less_or_equal_20)
{
#line 832
float num1 = 104232346.34534534;
float num2 = 3.3453453234;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 0);

}
END_TEST

START_TEST(is_less_or_equal_21)
{
#line 841
float num1 = -3.34534534;
float num2 = 3.34534534;
s21_decimal dec1, dec2;
s21_from_float_to_decimal(num1, &dec1);
s21_from_float_to_decimal(num2, &dec2);
int res = s21_is_less_or_equal(dec1, dec2);
ck_assert_int_eq(res, 1);

}
END_TEST

START_TEST(is_less_or_equal_22)
{
#line 850
s21_decimal dec5 = {
    {12345, 0, 0, 0b00000000000001000000000000000000}};  //  1.2345
s21_decimal dec6 = {{12, 0, 0, 0b10000000000000010000000000000000}};  // -1.2;
ck_assert_int_eq(s21_is_less_or_equal(dec5, dec6), 0);
ck_assert_int_eq(s21_is_less_or_equal(dec6, dec5), 1);

s21_decimal dec7 = {
    {12345, 0, 0, 0b10000000000001000000000000000000}};  // -1.2345
s21_decimal dec8 = {{12, 0, 0, 0b00000000000000010000000000000000}};  //  1.2;
ck_assert_int_eq(s21_is_less_or_equal(dec7, dec8), 1);
ck_assert_int_eq(s21_is_less_or_equal(dec8, dec7), 0);

s21_decimal dec1 = {
    {12345, 0, 0, 0b00000000000001000000000000000000}};  //  1.2345
s21_decimal dec2 = {{12, 0, 0, 0b00000000000000010000000000000000}};  //  1.2;
ck_assert_int_eq(s21_is_less_or_equal(dec1, dec2), 0);
ck_assert_int_eq(s21_is_less_or_equal(dec2, dec1), 1);

s21_decimal dec3 = {
    {12345, 0, 0, 0b10000000000001000000000000000000}};  // -1.2345
s21_decimal dec4 = {
    {12, 0, 0, 0b10000000000000010000000000000000}};  //  -1.2;
ck_assert_int_eq(s21_is_less_or_equal(dec3, dec4), 1);
ck_assert_int_eq(s21_is_less_or_equal(dec4, dec3), 0);

s21_decimal dec9 = {{12345, 0, 0, 0}};
s21_decimal dec10 = {{12345, 0, 0, 0}};
ck_assert_int_eq(s21_is_less_or_equal(dec9, dec10), 1);
ck_assert_int_eq(s21_is_less_or_equal(dec10, dec9), 1);

s21_decimal dec11 = {{0, 0, 0, 0}};
s21_decimal dec12 = {{0, 0, 0, 0}};
ck_assert_int_eq(s21_is_less_or_equal(dec11, dec12), 1);
ck_assert_int_eq(s21_is_less_or_equal(dec12, dec11), 1);

}
END_TEST

START_TEST(is_less_or_equal_27)
{
#line 886
// 3586
s21_decimal src1, src2;
// src1 = 0;
// src2 = 0;

src1.bits[0] = 0b00000000000000000000000000000000;
src1.bits[1] = 0b00000000000000000000000000000000;
src1.bits[2] = 0b00000000000000000000000000000000;
src1.bits[3] = 0b00000000000000000000000000000000;
src2.bits[0] = 0b00000000000000000000000000000000;
src2.bits[1] = 0b00000000000000000000000000000000;
src2.bits[2] = 0b00000000000000000000000000000000;
src2.bits[3] = 0b00000000000000000000000000000000;
int result = s21_is_less_or_equal(src1, src2);
int origin = 1;
ck_assert_int_eq(result, origin);

}
END_TEST

START_TEST(is_less_or_equal_23)
{
#line 904
// 3658
s21_decimal src1, src2;
// src1 = 665464545;
// src2 = 8798232189789785;

src1.bits[0] = 0b00100111101010100010111011100001;
src1.bits[1] = 0b00000000000000000000000000000000;
src1.bits[2] = 0b00000000000000000000000000000000;
src1.bits[3] = 0b00000000000000000000000000000000;
src2.bits[0] = 0b00010000010100101110011001011001;
src2.bits[1] = 0b00000000000111110100000111110010;
src2.bits[2] = 0b00000000000000000000000000000000;
src2.bits[3] = 0b00000000000000000000000000000000;
int result = s21_is_less_or_equal(src1, src2);
int origin = 1;
ck_assert_int_eq(result, origin);

}
END_TEST

START_TEST(is_less_or_equal_24)
{
#line 922
// 3676
s21_decimal src1, src2;
// src1 = 2.7986531268974139743;
// src2 = 9.979623121254565121244554;

src1.bits[0] = 0b11111110100100001101100101011111;
src1.bits[1] = 0b10000100011001000010000111101000;
src1.bits[2] = 0b00000000000000000000000000000001;
src1.bits[3] = 0b00000000000100110000000000000000;
src2.bits[0] = 0b11010100101011100011110110001010;
src2.bits[1] = 0b01110100000101000010011110100011;
src2.bits[2] = 0b00000000000010000100000101000100;
src2.bits[3] = 0b00000000000110000000000000000000;
int result = s21_is_less_or_equal(src1, src2);
int origin = 1;
ck_assert_int_eq(result, origin);

}
END_TEST

START_TEST(is_less_or_equal_25)
{
#line 940
// 3730
s21_decimal src1, src2;
// src1 = -0.77545545454546589781;
// src2 = 87894515154546456456;

src1.bits[0] = 0b10101100001010000001100001010101;
src1.bits[1] = 0b00110100001010010001111010111100;
src1.bits[2] = 0b00000000000000000000000000000100;
src1.bits[3] = 0b10000000000101000000000000000000;
src2.bits[0] = 0b00010011111011011111011110001000;
src2.bits[1] = 0b11000011110010000000101111011001;
src2.bits[2] = 0b00000000000000000000000000000100;
src2.bits[3] = 0b00000000000000000000000000000000;
int result = s21_is_less_or_equal(src1, src2);
int origin = 1;
ck_assert_int_eq(result, origin);






}
END_TEST


START_TEST(negate1)
{
#line 967
s21_decimal a = {{1, 1, 1, 0}};
s21_decimal b;
ck_assert_int_eq(s21_negate(a, &b), 0);
chang_sign(&a);
ck_assert_int_eq(s21_is_equal(b, a), 1);

}
END_TEST

START_TEST(negate2)
{
#line 974
s21_decimal a = {{1, 1, 1, 0}};
s21_decimal b;
chang_sign(&a);
ck_assert_int_eq(s21_negate(a, &b), 0);
chang_sign(&a);
ck_assert_int_eq(s21_is_equal(b, a), 1);

}
END_TEST

START_TEST(truncate1)
{
#line 984
s21_decimal a = {{1456789436, 0, 0, 0}};
s21_decimal b;
s21_decimal a1 = {{14567, 0, 0, 0}};
chang_sign(&a);
chang_sign(&a1);
set_exp(&a, 5);
ck_assert_int_eq(s21_truncate(a, &b), 0);
ck_assert_int_eq(s21_is_equal(b, a1), 1);

}
END_TEST

START_TEST(truncate__100_tests)
{
#line 994
srand(time(NULL));
int ran = rand();
int exp = rand() % 9;
int r = (int)(ran / pow(10, exp));
s21_decimal a, a1, b;
s21_from_int_to_decimal(r, &a1);
s21_from_int_to_decimal(ran, &a);
set_exp(&a, exp);
if (rand() % 6 <= 4) {
  chang_sign(&a);
  chang_sign(&a1);
}
ck_assert_int_eq(s21_truncate(a, &b), 0);
ck_assert_int_eq(s21_is_equal(b, a1), 1);

}
END_TEST

START_TEST(round__100_tests)
{
#line 1012
float n = Rand_R(-8388608, 8388608);
s21_decimal var;
float value = 0;
s21_from_float_to_decimal(n, &var);
s21_round(var, &var);
s21_from_decimal_to_float(var, &value);
ck_assert_float_eq_tol(round(n), value, 10);

}
END_TEST

START_TEST(round1)
{
#line 1021
s21_decimal var;
float value = 0;
s21_from_float_to_decimal(5.5, &var);
s21_round(var, &var);
s21_from_decimal_to_float(var, &value);
ck_assert_float_eq_tol(6.0, value, 10e-5);

}
END_TEST

START_TEST(floor_1)
{
#line 1031
float n = 744367.68425;
s21_decimal var;
float value = 0;
s21_from_float_to_decimal(n, &var);
s21_floor(var, &var);
s21_from_decimal_to_float(var, &value);
ck_assert_float_eq_tol(floor(n), value, 10e-1);

}
END_TEST

START_TEST(floor_coverage)
{
#line 1040
// если ошибка, то from_float_to_decimal не обрабатывает отрицательные
float n = -744367.68425;
s21_decimal var;
float value = 0;
s21_from_float_to_decimal(n, &var);
s21_floor(var, &var);
s21_from_decimal_to_float(var, &value);
ck_assert_float_eq_tol(floor(n), value, 10e-1);


}
END_TEST

START_TEST(from_float_to_decimal_1)
{
#line 1054
float a = 153914752.5555000;
float b;
s21_decimal a_dec;
s21_from_float_to_decimal(a, &a_dec);
s21_from_decimal_to_float(a_dec, &b);
ck_assert_float_eq_tol(a, b, 30);

}
END_TEST

START_TEST(from_float_to_decimal_2)
{
#line 1062
float n = Rand_R(-10, 10);
s21_decimal var;
float value = 0;
s21_from_float_to_decimal(n, &var);
s21_from_decimal_to_float(var, &value);
ck_assert_float_eq_tol(n, value, 1e-8);

}
END_TEST

START_TEST(from_float_to_decimal_6)
{
#line 1070
float a = 0.0000000000000000000000000001;
float b;
s21_decimal a_dec;
s21_from_float_to_decimal(a, &a_dec);
s21_from_decimal_to_float(a_dec, &b);
ck_assert_float_eq_tol(a, b, 30);

}
END_TEST

START_TEST(from_float_to_decimal_7)
{
#line 1078
float a = 0.000000000000000000000000000001;
float b;
s21_decimal a_dec;
s21_from_float_to_decimal(a, &a_dec);
s21_from_decimal_to_float(a_dec, &b);
ck_assert_float_eq_tol(a, b, 30);

}
END_TEST

START_TEST(from_float_to_decimal_8)
{
#line 1086
float a = -7922815779189785472389873664100.0f;
s21_decimal a_dec;
ck_assert_int_eq(s21_from_float_to_decimal(a, &a_dec), 1);

}
END_TEST

START_TEST(from_float_to_decimal_9)
{
#line 1091
s21_decimal var;
float val = NEG_INF;
ck_assert_int_eq(s21_from_float_to_decimal(val, &var), 1);

}
END_TEST

START_TEST(from_float_to_decimal_10)
{
#line 1096
s21_decimal var;
float val = S21_NAN;
ck_assert_int_eq(s21_from_float_to_decimal(val, &var), 1);

}
END_TEST

START_TEST(from_float_to_decimal_3)
{
#line 1101
float val = 0;
ck_assert_int_eq(s21_from_float_to_decimal(val, NULL), 1);

}
END_TEST

START_TEST(from_float_to_decimal_4)
{
#line 1105
s21_decimal var;
float a = 0.0;
ck_assert_int_eq(s21_from_float_to_decimal(a, &var), 0);

}
END_TEST

START_TEST(from_float_to_decimal_5)
{
#line 1110
s21_decimal var;
float a = -0.0;
ck_assert_int_eq(s21_from_float_to_decimal(a, &var), 0);

}
END_TEST

START_TEST(from_float_to_decimal_2_negative)
{
#line 1115
float n = -8.1234;
s21_decimal var;
float value = 0;
s21_from_float_to_decimal(n, &var);
s21_from_decimal_to_float(var, &value);
ck_assert_float_eq(n, value);

}
END_TEST

START_TEST(from_float_to_decimal_2_negative2)
{
#line 1123
float n = -8.4773;
s21_decimal var;
float value = 0;
s21_from_float_to_decimal(n, &var);
s21_from_decimal_to_float(var, &value);
ck_assert_float_eq_tol(n, value, 1e-8);

}
END_TEST

START_TEST(from_decimal_to_float_1)
{
#line 1131
s21_decimal var = {{1, 0, 0, 134217728}};
ck_assert_int_eq(s21_from_decimal_to_float(var, NULL), 1);

}
END_TEST

START_TEST(from_decimal_to_float_2)
{
#line 1135
s21_decimal var = {{1, 0, 0, 134217728}};
float value = 0;
ck_assert_int_eq(s21_from_decimal_to_float(var, &value), 1);

}
END_TEST

START_TEST(from_decimal_to_int_1)
{
#line 1140
s21_decimal var = {{1, 0, 0, 134217728}};
ck_assert_int_eq(s21_from_decimal_to_int(var, NULL), 1);

}
END_TEST

START_TEST(from_decimal_to_int_2)
{
#line 1144
s21_decimal var = {{1, 0, 0, 134217727}};
int val = 0;
ck_assert_int_eq(s21_from_decimal_to_int(var, &val), 1);

}
END_TEST

START_TEST(from_decimal_to_int_3)
{
#line 1149
s21_decimal var = {{1, 1, 1, 134217728}};
int a = 0;
ck_assert_int_eq(s21_from_decimal_to_int(var, &a), 1);

}
END_TEST

START_TEST(from_int_to_decimal_1)
{
#line 1154
int a = 0;
ck_assert_int_eq(s21_from_int_to_decimal(a, NULL), 1);

}
END_TEST

START_TEST(add__error_mark)
{
#line 1161
s21_decimal a = {{2147483647, 85365008, -1, 0}};
s21_decimal b = {{1039012127, 388364480, 803205246, 0}};
s21_decimal res;
ck_assert_int_eq(s21_add(a, b, &res), 1);

}
END_TEST

START_TEST(add__signs1)
{
#line 1167
s21_decimal a = {{ 20, 0, 0, 0 }};
s21_decimal b = {{ 10, 0, 0, 0 }};
s21_decimal c = {{ 30, 0, 0, 0 }};
chang_sign(&a);
chang_sign(&b);
chang_sign(&c);
ck_assert_int_eq(s21_add(a, b, &a), 0);
ck_assert_int_eq(s21_is_equal(a, c), 1);

}
END_TEST

START_TEST(add__signs2)
{
#line 1177
s21_decimal b = {{ 20, 0, 0, 0 }};
s21_decimal a = {{ 10, 0, 0, 0 }};
s21_decimal c = {{ 30, 0, 0, 0 }};
chang_sign(&a);
chang_sign(&b);
chang_sign(&c);
ck_assert_int_eq(s21_add(a, b, &a), 0);
ck_assert_int_eq(s21_is_equal(a, c), 1);

}
END_TEST

START_TEST(add__signs3)
{
#line 1187
s21_decimal b = {{ 20, 0, 0, 0 }};
s21_decimal a = {{ 10, 0, 0, 0 }};
s21_decimal c = {{ 10, 0, 0, 0 }};
chang_sign(&a);
ck_assert_int_eq(s21_add(a, b, &a), 0);
ck_assert_int_eq(s21_is_equal(a, c), 1);

}
END_TEST

START_TEST(add__signs4)
{
#line 1195
s21_decimal b = {{ 20, 0, 0, 0 }};
s21_decimal a = {{ 10, 0, 0, 0 }};
s21_decimal c = {{ 10, 0, 0, 0 }};
chang_sign(&a);
chang_sign(&c);
ck_assert_int_eq(s21_add(a, b, &a), 0);
ck_assert_int_eq(s21_is_equal(a, c), 0);

}
END_TEST

START_TEST(add__signs5)
{
#line 1204
s21_decimal b = {{ 20, 0, 0, 0 }};
s21_decimal a = {{ 10, 0, 0, 0 }};
s21_decimal c = {{ 10, 0, 0, 0 }};
chang_sign(&b);
chang_sign(&c);
ck_assert_int_eq(s21_add(a, b, &a), 0);
ck_assert_int_eq(s21_is_equal(a, c), 1);

}
END_TEST

START_TEST(add__error_mark2)
{
#line 1213
s21_decimal a = {{1, 0, 0, 0}};
s21_decimal b = {{21, 0, 0, 0}};
s21_decimal c = {{20, 0, 0, 0}};
chang_sign(&a);
s21_decimal res;
ck_assert_int_eq(s21_add(a, b, &res), 0);
ck_assert_int_eq(s21_is_equal(res, c), 1);

}
END_TEST

START_TEST(add__zero_plus_zero)
{
#line 1222
s21_decimal a = {{0, 0, 0, 0}};
s21_decimal b = {{0, 0, 0, 0}};
s21_decimal res;
ck_assert_int_eq(s21_add(a, b, &res), 0);
ck_assert_int_eq(s21_is_equal(a, res), 1);

}
END_TEST

START_TEST(add__100_tests)
{
#line 1229
int a = (int)Rand_R(-10e5, 10e1);
int b = (int)Rand_R(-10e5, 10e1);
int c = 0;

s21_decimal _a;
s21_decimal _b;
s21_decimal res;

s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
//print_decimal_bin(_a);
s21_add(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
ck_assert_int_eq(a + b, c);

}
END_TEST

START_TEST(add__100_tests2)
{
#line 1245
int a = (int)Rand_R(0, 10e5);
int b = (int)Rand_R(0, 10e5);
int c = 0;

s21_decimal _a;
s21_decimal _b;
s21_decimal res;

s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_add(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
ck_assert_int_eq(a + b, c);

}
END_TEST

START_TEST(add__100_tests3)
{
#line 1260
float a = Rand_R(-10e8, 10e8);
float b = Rand_R(-10e8, 10e8);
float c = 0;

s21_decimal _a;
s21_decimal _b;
s21_decimal res;

s21_from_float_to_decimal(a, &_a);
s21_from_float_to_decimal(b, &_b);
s21_add(_a, _b, &res);
s21_from_decimal_to_float(res, &c);
ck_assert_float_eq_tol(a + b, c, 10e2);


}
END_TEST

START_TEST(add__degree)
{
#line 1276
srand(time(NULL));
s21_decimal a = {{2147483647, 85365008, 330809813, 0}};
s21_decimal b = {{1039012127, 388364480, 803205246, 0}};
s21_decimal res;
s21_decimal zero = {{0, 0, 0, 0}};
  if (s21_add(a, b, &res) == 0) {
    ck_assert_int_eq(s21_add(a, b, &res), 0);
    if (check_sign(a) == 0 && check_sign(b) == 0) {
      ck_assert_int_eq(s21_is_greater(res, zero), 1);
    } else if (check_sign(a) == 1 && check_sign(b) == 1) {
      ck_assert_int_eq(s21_is_less(res, zero), 1);
    } else {
      s21_decimal one;
      s21_decimal two;
      if (check_sign(a) == 1) {
        chang_sign(&a);
        one = a;
        two = b;
      }
      if (check_sign(b) == 1) {
        chang_sign(&b);
        one = b;
        two = a;
      }
      if (s21_is_greater(one, two) == 1)
        ck_assert_int_eq(s21_is_less(one, res), s21_is_less(res, zero));
      else if (s21_is_greater(two, one) == 1)
        ck_assert_int_eq(s21_is_less(zero, res), s21_is_less(res, two));
    }
  } else {
    ck_assert_int_eq(s21_add(a, b, &res), 1);
  }

}
END_TEST

START_TEST(add_test_10)
{
#line 1310
int num1 = 42;
int num2 = 30;
int sum_int = 72;
s21_decimal a, b;
s21_from_int_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
int res_int = 0;
s21_add(a, b, &res_dec);
s21_from_decimal_to_int(res_dec, &res_int);
ck_assert_int_eq(res_int, sum_int);
ck_assert_int_eq(s21_add(a, b, &res_dec), 0);

}
END_TEST

START_TEST(add_test_11)
{
#line 1324
int num1 = 1000;
int num2 = 2000;
int sum_int = 3000;
s21_decimal a, b;
s21_from_int_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
int res_int = 0;
s21_add(a, b, &res_dec);
s21_from_decimal_to_int(res_dec, &res_int);
ck_assert_int_eq(res_int, sum_int);

}
END_TEST

START_TEST(add_test_12)
{
#line 1337
s21_decimal src1 = {0};
src1.bits[0] = 0b00000000000000000000001111111111;
src1.bits[1] = 0b00000000000000000000000000000000;
src1.bits[2] = 0b00000000000000000000000000000000;
src1.bits[3] = 0b00000000000000010000000000000000;
s21_decimal src2 = {0};
src2.bits[0] = 0b00000000000000000000001111111111;
src2.bits[1] = 0b00000000000000000000000000000000;
src2.bits[2] = 0b00000000000000000000000000000000;
src2.bits[3] = 0b00000000000000100000000000000000;
s21_decimal original_res = {0};
original_res.bits[0] = 0b00000000000000000010101111110101;
original_res.bits[1] = 0b00000000000000000000000000000000;
original_res.bits[2] = 0b00000000000000000000000000000000;
original_res.bits[3] = 0b00000000000000100000000000000000;
s21_decimal s21_res = {0};
s21_add(src1, src2, &s21_res);
ck_assert_int_eq(s21_add(src1, src2, &s21_res), 0);
ck_assert_int_eq(original_res.bits[0], s21_res.bits[0]);
ck_assert_int_eq(original_res.bits[1], s21_res.bits[1]);
ck_assert_int_eq(original_res.bits[2], s21_res.bits[2]);
ck_assert_int_eq(original_res.bits[3], s21_res.bits[3]);

}
END_TEST

START_TEST(add_test_13)
{
#line 1361
s21_decimal src1 = {0};
src1.bits[0] = 0b11111111111111111111111111111111;
src1.bits[1] = 0b11111111111111111111111111111111;
src1.bits[2] = 0b11111111111111111111111111111111;
src1.bits[3] = 0b10000000000000000000000000000000;
s21_decimal src2 = {0};
src2.bits[0] = 0b00000000000000000000000000000001;
src2.bits[1] = 0b00000000000000000000000000000000;
src2.bits[2] = 0b00000000000000000000000000000000;
src2.bits[3] = 0b00000000000000000000000000000000;
s21_decimal original_res = {0};
original_res.bits[0] = 0b11111111111111111111111111111110;
original_res.bits[1] = 0b11111111111111111111111111111111;
original_res.bits[2] = 0b11111111111111111111111111111111;
original_res.bits[3] = 0b10000000000000000000000000000000;
s21_decimal s21_res = {0};
s21_add(src1, src2, &s21_res);
ck_assert_int_eq(s21_add(src1, src2, &s21_res), 0);
ck_assert_int_eq(original_res.bits[0], s21_res.bits[0]);
ck_assert_int_eq(original_res.bits[1], s21_res.bits[1]);
ck_assert_int_eq(original_res.bits[2], s21_res.bits[2]);
ck_assert_int_eq(original_res.bits[3], s21_res.bits[3]);

}
END_TEST

START_TEST(add_test_14)
{
#line 1385
s21_decimal c = {{S21_MAX_UINT, 0, 0, 0}};
s21_decimal d = {{1, 0, 0, 0}};
s21_decimal etalon = {{0, 1, 0, 0}};

s21_decimal res = {{0, 0, 0, 0}};
s21_decimal* p_res = &res;

// 0 - OK 1 - число слишком велико или равно бесконечности 2 - число слишком
// мало или равно отрицательной бесконечности 3 - деление на 0
int add = s21_add(c, d, p_res);
ck_assert_int_eq(add, 0);

ck_assert_int_eq(res.bits[3], etalon.bits[3]);
ck_assert_int_eq(res.bits[2], etalon.bits[2]);
ck_assert_int_eq(res.bits[1], etalon.bits[1]);
ck_assert_int_eq(res.bits[0], etalon.bits[0]);

int equal =
    s21_is_equal(res, etalon);  // Возвращаемое значение: 0 - 0 1 - 1
ck_assert_int_eq(equal, 1);

}
END_TEST

START_TEST(add_test_15)
{
#line 1407
s21_decimal c = {{0b00000000000000000001100101111001, 0, 0, 0}};
s21_decimal d = {{0b00000000000000010010000110001001, 0, 0, 0}};
s21_decimal etalon = {{0b00000000000000010011101100000010, 0, 0, 0}};

s21_decimal res = {{0, 0, 0, 0}};
s21_decimal* p_res = &res;

// 0 - OK 1 - число слишком велико или равно бесконечности 2 - число слишком
// мало или равно отрицательной бесконечности 3 - деление на 0
int add = s21_add(c, d, p_res);
ck_assert_int_eq(add, 0);

int equal =
    s21_is_equal(res, etalon);  // Возвращаемое значение: 0 - 0 1 - 1
ck_assert_int_eq(equal, 1);

}
END_TEST

START_TEST(add_test_16)
{
#line 1424
s21_decimal c = {0};
c.bits[0] = 0b11111111111111111111111111111110;
c.bits[1] = 0b00000000000000000000000000000000;
c.bits[2] = 0b00000000000000000000000000000000;
c.bits[3] = 0b00000000000000000000000000000000;
s21_decimal d = {{1, 0, 0, 0}};
s21_decimal etalon = {0};
etalon.bits[0] = 0b11111111111111111111111111111111;
etalon.bits[1] = 0b00000000000000000000000000000000;
etalon.bits[2] = 0b00000000000000000000000000000000;
etalon.bits[3] = 0b00000000000000000000000000000000;
s21_decimal res = {{0, 0, 0, 0}};
s21_decimal* p_res = &res;

// 0 - OK 1 - число слишком велико или равно бесконечности 2 - число слишком
// мало или равно отрицательной бесконечности 3 - деление на 0
int add = s21_add(c, d, p_res);
ck_assert_int_eq(add, 0);

ck_assert_int_eq(res.bits[0], etalon.bits[0]);
ck_assert_int_eq(res.bits[1], etalon.bits[1]);
ck_assert_int_eq(res.bits[2], etalon.bits[2]);
ck_assert_int_eq(res.bits[3], etalon.bits[3]);

}
END_TEST

START_TEST(add_test_17)
{
#line 1449
s21_decimal c = {{0, 0, S21_MAX_UINT - 1, 0}};
s21_decimal d = {{0, 0, 1, 0}};
s21_decimal etalon = {{0, 0, S21_MAX_UINT, 0}};

s21_decimal res = {{0, 0, 0, 0}};
s21_decimal* p_res = &res;

// 0 - OK 1 - число слишком велико или равно бесконечности 2 - число слишком
// мало или равно отрицательной бесконечности 3 - деление на 0
int add = s21_add(c, d, p_res);
ck_assert_int_eq(add, 0);

int equal =
    s21_is_equal(res, etalon);  // Возвращаемое значение: 0 - 0 1 - 1
ck_assert_int_eq(equal, 1);

}
END_TEST

START_TEST(add_test_18)
{
#line 1466
s21_decimal c = {{1, 0, 0, 0}};
s21_decimal d = {{1, 0, 0, 0}};
s21_decimal etalon = {{2, 0, 0, 0}};

s21_decimal res = {{0, 0, 0, 0}};
s21_decimal* p_res = &res;

// 0 - OK 1 - число слишком велико или равно бесконечности 2 - число слишком
// мало или равно отрицательной бесконечности 3 - деление на 0
int add = s21_add(c, d, p_res);
ck_assert_int_eq(add, 0);

int equal =
    s21_is_equal(res, etalon);  // Возвращаемое значение: 0 - 0 1 - 1
ck_assert_int_eq(equal, 1);

}
END_TEST

START_TEST(add_test_19)
{
#line 1483
s21_decimal c = {{1000, 0, 0, 0}};
s21_decimal d = {{1000, 0, 0, 0}};
s21_decimal etalon = {{2000, 0, 0, 0}};
s21_decimal result = {{0, 0, 0, 0}};
s21_decimal* p_result = &result;
// 0 - OK 1 - число слишком велико или равно бесконечности 2 - число слишком
// мало или равно отрицательной бесконечности 3 - деление на 0
int add = s21_add(c, d, p_result);
ck_assert_int_eq(add, 0);
// Возвращаемое значение: 0 - 0 1 - 1
int equal = s21_is_equal(result, etalon);
ck_assert_int_eq(equal, 1);

}
END_TEST

START_TEST(add_test_20)
{
#line 1497
s21_decimal c = {{5, 0, 0, 0}};
s21_decimal d = {{5, 0, 0, 0}};
s21_decimal etalon = {{10, 0, 0, 0}};
s21_decimal res = {{0, 0, 0, 0}};
s21_decimal* p_res = &res;
// 0 - OK 1 - число слишком велико или равно бесконечности
// 2 - число слишком мало или равно отрицательной бесконечности
// 3 - деление на 0
int add = s21_add(c, d, p_res);
int equal =
    s21_is_equal(res, etalon);  // Возвращаемое значение: 0 - 0 1 - 1
ck_assert_int_eq(add, 0);
ck_assert_int_eq(equal, 1);


}
END_TEST

START_TEST(sub__zero)
{
#line 1515
srand(time(NULL));
s21_decimal a = {{rand(), rand(), rand(), 0}};
s21_decimal zero = {{0, 0, 0, 0}};
ck_assert_int_eq(s21_sub(a, a, &a), 0);
ck_assert_int_eq(s21_is_equal(a, zero), 1);
  
}
END_TEST

START_TEST(sub__error_mark)
{
#line 1522
srand(time(NULL));
s21_decimal a = {{rand(), rand(), -9, 0}};
s21_decimal b = {{rand(), rand(), -1, 0}};
chang_sign(&b);
ck_assert_int_eq(s21_sub(a, b, &a), 1);

}
END_TEST

START_TEST(sub__error_mark2)
{
#line 1529
srand(time(NULL));
s21_decimal a = {{rand(), rand(), -9, 0}};
s21_decimal b = {{rand(), rand(), -1, 0}};
chang_sign(&a);
ck_assert_int_eq(s21_sub(a, b, &a), 1);

}
END_TEST

START_TEST(sub__error_mark3)
{
#line 1536
srand(time(NULL));
s21_decimal a = {{1, 0, 0, 0}};
s21_decimal b = {{10, 0, 0, 0}};
chang_sign(&b);
ck_assert_int_eq(sub_lite(a, b, &a), 1);

}
END_TEST

START_TEST(sub__error_mark4)
{
#line 1543
srand(time(NULL));
s21_decimal a = {{1, 0, 0, 0}};
s21_decimal b = {{21, 0, 0, 0}};
s21_decimal c = {{20, 0, 0, 0}};
chang_sign(&b);
chang_sign(&a);
ck_assert_int_eq(s21_sub(a, b, &a), 0);
ck_assert_int_eq(s21_is_equal(a, c), 1);

}
END_TEST

START_TEST(sub__error_mark5)
{
#line 1553
srand(time(NULL));
s21_decimal a = {{1, 0, 0, 0}};
s21_decimal b = {{21, 0, 0, 0}};
s21_decimal c = {{20, 0, 0, 0}};
chang_sign(&b);
chang_sign(&a);
chang_sign(&c);
ck_assert_int_eq(s21_sub(b, a, &a), 0);
ck_assert_int_eq(s21_is_equal(a, c), 1);

}
END_TEST

START_TEST(sub__100_tests)
{
#line 1564
srand(time(NULL));
s21_decimal a = {{rand(), rand(), rand(), 0}};
s21_decimal b = {{rand(), rand() % 2, rand(), 0}};
s21_decimal res;
s21_decimal ser;
int point;
//if (rand() % 6 <= 4)
//  chang_sign(&a);
//int s2 = rand() % 9;
//if (s2 > 3 && s2 < 7)
//  chang_sign(&b);
set_exp(&a,rand() % 28);
set_exp(&b,rand() % 28);
//printf("%d", _i);
//print_decimal_int(a);
//print_decimal_int(b);
if ((point = s21_sub(a, b, &res)) == 0) {
  ck_assert_int_eq(point, 0);
  if (check_sign(a) == 1 && check_sign(b) == 1) {
    chang_sign(&a);
    chang_sign(&b);
    ck_assert_int_eq(s21_sub(b, a, &ser), 0);
    ck_assert_int_eq(s21_is_equal(res, ser), 1);
  } else if (check_sign(a) == 1) {
    chang_sign(&a);
    if ((point = s21_add(a, b, &ser)) == 1) {
    ck_assert_int_eq(point, 1);  
    } else {
      ck_assert_int_eq(point, 0);
      ck_assert_int_eq(s21_negate(ser, &ser), 0);
      ck_assert_int_eq(s21_is_equal(res, ser), 1);
    }
  } else if (check_sign(b) == 1) {
    chang_sign(&b);
    if ((point = s21_add(a, b, &ser)) == 1) {
    ck_assert_int_eq(point, 1);  
    } else {
      ck_assert_int_eq(point, 0);
      ck_assert_int_eq(s21_is_equal(res, ser), 1);
    }
  }
} else {
  ck_assert_int_ne(point, 0);
}


}
END_TEST

START_TEST(mul_test1)
{
#line 1613
int a = -1;
int b = -1;
int c = 0;
s21_decimal _a;
s21_decimal _b;
s21_decimal res;

s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_mul(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
ck_assert_int_eq(a * b, (int)(c));

}
END_TEST

START_TEST(mul_test2)
{
#line 1627
int a = -1;
int b = -2;
int c = 0;
s21_decimal _a;
s21_decimal _b;
s21_decimal res;

s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_mul(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
ck_assert_int_eq(a * b, (int)(c));

}
END_TEST

START_TEST(mul_test3)
{
#line 1641
int a = -2;
int b = -1;
int c = 0;
s21_decimal _a;
s21_decimal _b;
s21_decimal res;

s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_mul(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
ck_assert_int_eq(a * b, (int)(c));


}
END_TEST

START_TEST(mul__100_tests)
{
#line 1656
int a = (int)Rand_R(-10e3, 10e3);
int b = (int)Rand_R(-10e3, 10e3);
int c = 0;

s21_decimal _a;
s21_decimal _b;
s21_decimal res;

s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
//print_decimal_bin(_a);
//print_decimal_bin(_b);
s21_mul(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
ck_assert_int_eq(a * b, c);


}
END_TEST

START_TEST(mul2__100_tests2)
{
#line 1674
int a = (int)Rand_R(-10e3, 10e3);
int b = (int)Rand_R(-10e3, 10e3);
int c = 0;
s21_decimal _a;
s21_decimal _b;
s21_decimal res;
s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_mul(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
if (a * b != (int)(c)) {
  printf("%d * %d\n", a, b);
}
ck_assert_int_eq(a * b, (int)(c));

}
END_TEST

START_TEST(mul2__100_tests3)
{
#line 1690
s21_decimal _a = {{100, 0, 0, 0}};
set_exp(&_a, 1);
s21_decimal _b ={{10, 0, 0, 0}};
s21_decimal res ={{100, 0, 0, 0}};
ck_assert_int_eq(s21_mul(_a, _b, &_a), 0);
ck_assert_int_eq(s21_is_equal(res, _a), 1);

}
END_TEST

START_TEST(mul2__100_tests4)
{
#line 1698
int a = (int)Rand_R(-10e3, 0);
int b = (int)Rand_R(-10e3, 0);
int c = 0;
s21_decimal _a;
s21_decimal _b;
s21_decimal res;
s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_mul(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
if (a * b != (int)(c)) {
  printf("%d * %d\n", a, b);
}
ck_assert_int_eq(a * b, (int)(c));

}
END_TEST

START_TEST(mul2__100_tests5)
{
#line 1714
int a = (int)Rand_R(0, 10e3);
int b = (int)Rand_R(0, 10e3);
int c = 0;
s21_decimal _a;
s21_decimal _b;
s21_decimal res;
s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_mul(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
if (a * b != (int)(c)) {
  printf("%d * %d\n", a, b);
}
ck_assert_int_eq(a * b, (int)(c));

}
END_TEST

START_TEST(mul2_tests4)
{
#line 1730
s21_decimal _a = {{100, 0, 0, 0}};
set_exp(&_a, 28);
s21_decimal _b ={{10, 0, 0, 0}};
set_exp(&_b, 15);
s21_decimal res ={{0, 0, 0, 0}};
ck_assert_int_eq(s21_mul(_a, _b, &_a), 0);
ck_assert_int_eq(s21_is_equal(res, _a), 1);

}
END_TEST

START_TEST(mul_test6)
{
#line 1739
int num1 = -10;
int num2 = 20;
int prod_int = -200;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_int_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
int res_int = 0;
s21_mul(a, b, &res_dec);
ck_assert_int_eq(s21_from_decimal_to_int(res_dec, &res_int), 0);
ck_assert_int_eq(res_int, prod_int);

}
END_TEST

START_TEST(mul_test7)
{
#line 1753
float num1 = 9403.0e2;
float num2 = 9403.0e2;
float res_origin = 884164090000;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_float_to_decimal(num1, &a);
s21_from_float_to_decimal(num2, &b);
s21_decimal res_dec = {0};
float res_float = 0;
s21_mul(a, b, &res_dec);
s21_from_decimal_to_float(res_dec, &res_float);
ck_assert_float_eq(res_float, res_origin);

}
END_TEST

START_TEST(mul_test8)
{
#line 1767
float num1 = 9403.0e2;
int num2 = 202;
float res_origin = 189940600;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_float_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
float res_float = 0;
s21_mul(a, b, &res_dec);
s21_from_decimal_to_float(res_dec, &res_float);
ck_assert_float_eq(res_float, res_origin);

}
END_TEST

START_TEST(mul_test9)
{
#line 1781
int num1 = -32768;
int num2 = 32768;
int res_origin = -1073741824;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_int_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
int res_int = 0;
s21_mul(a, b, &res_dec);
s21_from_decimal_to_int(res_dec, &res_int);
ck_assert_int_eq(res_int, res_origin);

}
END_TEST

START_TEST(mod__1)
{
#line 1797
int a = (int)Rand_R(-11, 10e3);
int b = (int)Rand_R(-10e3, -1);
int c = 0;
s21_decimal _a;
s21_decimal _b;
s21_decimal res;
s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_mod(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
ck_assert_int_eq(a % b, (int)(c));

}
END_TEST

START_TEST(mod__2)
{
#line 1810
int a = Rand_R(-10e8, 10e8);
int b = Rand_R(-10e8, 10e8);
int c = 0;
s21_decimal _a;
s21_decimal _b;
s21_decimal res;
s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_mod(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
ck_assert_int_eq((int)(a % b), c);

}
END_TEST

START_TEST(mod__3)
{
#line 1823
int a = Rand_R(-1000, 1000);
int b = Rand_R(-20, -1);
int c = 0;
s21_decimal _a;
s21_decimal _b;
s21_decimal res;
s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_mod(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
ck_assert_int_eq((a % b), c);

}
END_TEST

START_TEST(mod__4)
{
#line 1836
int a = Rand_R(-10e8, 0);
int b = Rand_R(-10e8, 0);
int c = 0;
s21_decimal _a;
s21_decimal _b;
s21_decimal res;
s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_mod(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
ck_assert_int_eq((a % b), c);

}
END_TEST

START_TEST(mod_5)
{
#line 1849
int num1 = 3;
int num2 = 2;
int res_origin = num1 % num2;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_int_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
int res_int = 0;
s21_mod(a, b, &res_dec);
s21_from_decimal_to_int(res_dec, &res_int);
ck_assert_int_eq(res_int, res_origin);

}
END_TEST

START_TEST(mod_6)
{
#line 1863
int num1 = -98765;
int num2 = 1234;
int res_origin = num1 % num2;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_int_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
int res_int = 0;
s21_mod(a, b, &res_dec);
s21_from_decimal_to_int(res_dec, &res_int);
ck_assert_int_eq(res_int, res_origin);

}
END_TEST

START_TEST(mod_7)
{
#line 1877
int num1 = 30198;
int num2 = 20210;
int res_origin = num1 % num2;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_int_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
int res_int = 0;
s21_mod(a, b, &res_dec);
s21_from_decimal_to_int(res_dec, &res_int);
ck_assert_int_eq(res_int, res_origin);

}
END_TEST

START_TEST(mod_8)
{
#line 1891
int num1 = 342576;
int num2 = 1542134;
int res_origin = num1 % num2;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_int_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
int res_int = 0;
s21_mod(a, b, &res_dec);
s21_from_decimal_to_int(res_dec, &res_int);
ck_assert_int_eq(res_int, res_origin);

}
END_TEST

START_TEST(mod_9)
{
#line 1905
int num1 = 98765;
int num2 = 127234;
int res_origin = num1 % num2;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_int_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
int res_int = 0;
s21_mod(a, b, &res_dec);
s21_from_decimal_to_int(res_dec, &res_int);
ck_assert_int_eq(res_int, res_origin);


}
END_TEST

START_TEST(div__1)
{
#line 1922
int a = (int)Rand_R(-10e3, 10e3);
int b = (int)Rand_R(-10e3, 10e3);
int c = 0;

s21_decimal _a;
s21_decimal _b;
s21_decimal res;

s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_div(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
ck_assert_int_eq(a / b, c);

}
END_TEST

START_TEST(div__2)
{
#line 1937
int a = (int)Rand_R(1, 10e3);
int b = (int)Rand_R(1, 10e3);
int c = 0;

s21_decimal _a;
s21_decimal _b;
s21_decimal res;

s21_from_int_to_decimal(a, &_a);
s21_from_int_to_decimal(b, &_b);
s21_div(_a, _b, &res);
s21_from_decimal_to_int(res, &c);
if (a / b != (int)(c)) {
  printf("%d * %d\n", a, b);
}
ck_assert_int_eq(a / b, (int)(c));

}
END_TEST

START_TEST(div__3)
{
#line 1955
s21_decimal dec1;
s21_decimal dec2;
int tmp1 = -100;
int tmp2 = -99999;
float res_s21 = 0;
float res = 0.00100001;
s21_from_int_to_decimal(tmp1, &dec1);
s21_from_int_to_decimal(tmp2, &dec2);
s21_decimal res1;
s21_div(dec1, dec2, &res1);
s21_from_decimal_to_float(res1, &res_s21);
ck_assert_float_eq_tol(res_s21, res, 6);

}
END_TEST

START_TEST(div__4)
{
#line 1969
s21_decimal dec1;
s21_decimal dec2;
int tmp1 = 100;
float tmp2 = 999.99;
float res_s21 = 0.0;
float res = 0.100001;
s21_from_int_to_decimal(tmp1, &dec1);
s21_from_float_to_decimal(tmp2, &dec2);
s21_decimal res1;
s21_div(dec1, dec2, &res1);
s21_from_decimal_to_float(res1, &res_s21);
ck_assert_float_eq_tol(res_s21, res, 6);

}
END_TEST

START_TEST(div__5)
{
#line 1983
s21_decimal dec1;
s21_decimal dec2;
int tmp1 = 100;
float tmp2 = 0;
s21_from_int_to_decimal(tmp1, &dec1);
s21_from_float_to_decimal(tmp2, &dec2);
s21_decimal res1;
ck_assert_int_eq(s21_div(dec1, dec2, &res1), 3);

}
END_TEST

START_TEST(div__6)
{
#line 1993
int num1 = 100;
int num2 = 50;
int res_origin = 2;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_int_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
int res_int = 0;
s21_div(a, b, &res_dec);
s21_from_decimal_to_int(res_dec, &res_int);
ck_assert_int_eq(res_int, res_origin);

}
END_TEST

START_TEST(div__7)
{
#line 2007
int num1 = -32768;
int num2 = 2;
int res_origin = -16384;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_int_to_decimal(num1, &a);
s21_from_int_to_decimal(num2, &b);
s21_decimal res_dec = {0};
int res_int = 0;
s21_div(a, b, &res_dec);
s21_from_decimal_to_int(res_dec, &res_int);
ck_assert_int_eq(res_int, res_origin);

}
END_TEST

START_TEST(div__8)
{
#line 2021
float num1 = -0.9;
float num2 = 0.000076;
float res_origin = num1 / num2;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_float_to_decimal(num1, &a);
s21_from_float_to_decimal(num2, &b);
s21_decimal res_dec = {0};
float res_float = 0;
s21_div(a, b, &res_dec);
s21_from_decimal_to_float(res_dec, &res_float);
ck_assert_float_eq(res_float, res_origin);

}
END_TEST

START_TEST(div__9)
{
#line 2035
float num1 = -0.9e3;
float num2 = 30.32;
float res_origin = num1 / num2;
s21_decimal a = {0};
s21_decimal b = {0};
s21_from_float_to_decimal(num1, &a);
s21_from_float_to_decimal(num2, &b);
s21_decimal res_dec = {0};
float res_float = 0;
s21_div(a, b, &res_dec);
s21_from_decimal_to_float(res_dec, &res_float);
ck_assert_float_eq_tol(res_float, res_origin, 1e-4);

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Comprased");
    TCase *tc1_1 = tcase_create("equal");
    TCase *tc1_2 = tcase_create("not_equal");
    TCase *tc1_3 = tcase_create("greater");
    TCase *tc1_4 = tcase_create("less");
    Suite *s2 = suite_create("Another");
    TCase *tc2_1 = tcase_create("neagte");
    TCase *tc2_2 = tcase_create("truncate");
    TCase *tc2_3 = tcase_create("round");
    TCase *tc2_4 = tcase_create("floor");
    Suite *s3 = suite_create("Convert");
    TCase *tc3_1 = tcase_create("from_float_to_decimal");
    Suite *s4 = suite_create("Arifmetic");
    TCase *tc4_1 = tcase_create("add");
    TCase *tc4_2 = tcase_create("sub");
    TCase *tc4_3 = tcase_create("mul");
    TCase *tc4_4 = tcase_create("mod");
    TCase *tc4_5 = tcase_create("div");
    SRunner *sr = srunner_create(s1);
    int nf;

    /* User-specified pre-run code */
#line 2049
//tcase_set_timeout(tc2_2, 10);
//tcase_set_timeout(tc3_1, 6);
//tcase_set_timeout(tc3_2, 10);

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, isequal__not_equal);
    tcase_add_test(tc1_1, isequal__equal);
    tcase_add_test(tc1_1, isequal__different_exp);
    suite_add_tcase(s1, tc1_2);
    tcase_add_test(tc1_2, isnot_equal__not_equal);
    tcase_add_test(tc1_2, isnot_equal__equal);
    tcase_add_test(tc1_2, isnot_equal__different_exp);
    tcase_add_test(tc1_2, isnot_equal__auto_generate);
    tcase_add_test(tc1_2, isnot_equal__auto);
    suite_add_tcase(s1, tc1_3);
    tcase_add_test(tc1_3, isgreater__sign);
    tcase_add_test(tc1_3, isgreater__1);
    tcase_add_test(tc1_3, isgreater__12);
    tcase_add_test(tc1_3, isgreater__13);
    tcase_add_test(tc1_3, isgreater__14);
    tcase_add_test(tc1_3, isgreater__15);
    tcase_add_test(tc1_3, isgreater__16);
    tcase_add_test(tc1_3, isgreater__17);
    tcase_add_test(tc1_3, isgreater__18);
    tcase_add_test(tc1_3, isgreater__0);
    tcase_add_test(tc1_3, isgreater__02);
    tcase_add_test(tc1_3, isgreater_or_equal__11);
    tcase_add_test(tc1_3, isgreater_or_equal__12);
    tcase_add_test(tc1_3, isgreater_or_equal__13);
    tcase_add_test(tc1_3, isgreater_or_equal__14);
    tcase_add_test(tc1_3, isgreater_or_equal__15);
    tcase_add_test(tc1_3, isgreater_or_equal__16);
    tcase_add_test(tc1_3, isgreater_or_equal__17);
    tcase_add_test(tc1_3, isgreater_or_equal__18);
    tcase_add_test(tc1_3, isgreater_or_equal__19);
    tcase_add_test(tc1_3, isgreater_or_equal_sign);
    tcase_add_test(tc1_3, isgreater_or_equal__0);
    tcase_add_test(tc1_3, isgreater_or_equal__auto);
    tcase_add_test(tc1_3, isgreater_or_equal__20);
    tcase_add_test(tc1_3, isgreater_or_equal__21);
    tcase_add_test(tc1_3, isgreater_or_equal__22);
    tcase_add_test(tc1_3, isgreater_or_equal__23);
    tcase_add_test(tc1_3, isgreater_or_equal__24);
    tcase_add_test(tc1_3, isgreater_or_equal__25);
    tcase_add_test(tc1_3, isgreater_or_equal__26);
    tcase_add_test(tc1_3, isgreater_or_equal__27);
    tcase_add_test(tc1_3, isgreater_or_equal__28);
    tcase_add_test(tc1_3, isgreater_or_equal__29);
    tcase_add_test(tc1_3, isgreater_or_equal__30);
    tcase_add_test(tc1_3, isgreater_or_equal__31);
    tcase_add_test(tc1_3, isgreater_or_equal__32);
    tcase_add_test(tc1_3, greater_test_1);
    tcase_add_test(tc1_3, greater_test_2);
    tcase_add_test(tc1_3, greater_test_3);
    tcase_add_test(tc1_3, greater_test_4);
    tcase_add_test(tc1_3, greater_test_5);
    suite_add_tcase(s1, tc1_4);
    tcase_add_test(tc1_4, isless_or_equal__11);
    tcase_add_test(tc1_4, isless_or_equal__12);
    tcase_add_test(tc1_4, isless_or_equal__13);
    tcase_add_test(tc1_4, isless_or_equal__14);
    tcase_add_test(tc1_4, isless_or_equal__15);
    tcase_add_test(tc1_4, isless_or_equal__16);
    tcase_add_test(tc1_4, isless_or_equal__17);
    tcase_add_test(tc1_4, isless_or_equal__18);
    tcase_add_test(tc1_4, isless_or_equal__19);
    tcase_add_test(tc1_4, isless_or_equal__110);
    tcase_add_test(tc1_4, isless_or_equal__0);
    tcase_add_test(tc1_4, isless__1);
    tcase_add_test(tc1_4, isless__12);
    tcase_add_test(tc1_4, isless__13);
    tcase_add_test(tc1_4, isless__14);
    tcase_add_test(tc1_4, isless__15);
    tcase_add_test(tc1_4, isless__16);
    tcase_add_test(tc1_4, isless__16_1);
    tcase_add_test(tc1_4, isless__16_2);
    tcase_add_test(tc1_4, isless__17);
    tcase_add_test(tc1_4, isless__18);
    tcase_add_test(tc1_4, isless__equal);
    tcase_add_test(tc1_4, isless__0);
    tcase_add_test(tc1_4, isless_1);
    tcase_add_test(tc1_4, isless_2);
    tcase_add_test(tc1_4, isless_3);
    tcase_add_test(tc1_4, isless_4);
    tcase_add_test(tc1_4, isless_5);
    tcase_add_test(tc1_4, isless_6);
    tcase_add_test(tc1_4, isless_7);
    tcase_add_test(tc1_4, isless_8);
    tcase_add_test(tc1_4, is_less_or_equal_1);
    tcase_add_test(tc1_4, is_less_or_equal_2);
    tcase_add_test(tc1_4, is_less_or_equal_3);
    tcase_add_test(tc1_4, is_less_or_equal_4);
    tcase_add_test(tc1_4, is_less_or_equal_5);
    tcase_add_test(tc1_4, is_less_or_equal_6);
    tcase_add_test(tc1_4, is_less_or_equal_7);
    tcase_add_test(tc1_4, is_less_or_equal_8);
    tcase_add_test(tc1_4, is_less_or_equal_9);
    tcase_add_test(tc1_4, is_less_or_equal_10);
    tcase_add_test(tc1_4, is_less_or_equal_11);
    tcase_add_test(tc1_4, is_less_or_equal_12);
    tcase_add_test(tc1_4, is_less_or_equal_13);
    tcase_add_test(tc1_4, is_less_or_equal_14);
    tcase_add_test(tc1_4, is_less_or_equal_15);
    tcase_add_test(tc1_4, is_less_or_equal_16);
    tcase_add_test(tc1_4, is_less_or_equal_17);
    tcase_add_test(tc1_4, is_less_or_equal_18);
    tcase_add_test(tc1_4, is_less_or_equal_19);
    tcase_add_test(tc1_4, is_less_or_equal_26);
    tcase_add_test(tc1_4, is_less_or_equal_20);
    tcase_add_test(tc1_4, is_less_or_equal_21);
    tcase_add_test(tc1_4, is_less_or_equal_22);
    tcase_add_test(tc1_4, is_less_or_equal_27);
    tcase_add_test(tc1_4, is_less_or_equal_23);
    tcase_add_test(tc1_4, is_less_or_equal_24);
    tcase_add_test(tc1_4, is_less_or_equal_25);
    suite_add_tcase(s2, tc2_1);
    tcase_add_test(tc2_1, negate1);
    tcase_add_test(tc2_1, negate2);
    suite_add_tcase(s2, tc2_2);
    tcase_add_test(tc2_2, truncate1);
    tcase_add_loop_test(tc2_2, truncate__100_tests, 0, 100);
    suite_add_tcase(s2, tc2_3);
    tcase_add_loop_test(tc2_3, round__100_tests, 0, 100);
    tcase_add_test(tc2_3, round1);
    suite_add_tcase(s2, tc2_4);
    tcase_add_test(tc2_4, floor_1);
    tcase_add_test(tc2_4, floor_coverage);
    suite_add_tcase(s3, tc3_1);
    tcase_add_test(tc3_1, from_float_to_decimal_1);
    tcase_add_loop_test(tc3_1, from_float_to_decimal_2, 0, 100);
    tcase_add_test(tc3_1, from_float_to_decimal_6);
    tcase_add_test(tc3_1, from_float_to_decimal_7);
    tcase_add_test(tc3_1, from_float_to_decimal_8);
    tcase_add_test(tc3_1, from_float_to_decimal_9);
    tcase_add_test(tc3_1, from_float_to_decimal_10);
    tcase_add_test(tc3_1, from_float_to_decimal_3);
    tcase_add_test(tc3_1, from_float_to_decimal_4);
    tcase_add_test(tc3_1, from_float_to_decimal_5);
    tcase_add_test(tc3_1, from_float_to_decimal_2_negative);
    tcase_add_test(tc3_1, from_float_to_decimal_2_negative2);
    tcase_add_test(tc3_1, from_decimal_to_float_1);
    tcase_add_test(tc3_1, from_decimal_to_float_2);
    tcase_add_test(tc3_1, from_decimal_to_int_1);
    tcase_add_test(tc3_1, from_decimal_to_int_2);
    tcase_add_test(tc3_1, from_decimal_to_int_3);
    tcase_add_test(tc3_1, from_int_to_decimal_1);
    suite_add_tcase(s4, tc4_1);
    tcase_add_test(tc4_1, add__error_mark);
    tcase_add_test(tc4_1, add__signs1);
    tcase_add_test(tc4_1, add__signs2);
    tcase_add_test(tc4_1, add__signs3);
    tcase_add_test(tc4_1, add__signs4);
    tcase_add_test(tc4_1, add__signs5);
    tcase_add_test(tc4_1, add__error_mark2);
    tcase_add_test(tc4_1, add__zero_plus_zero);
    tcase_add_loop_test(tc4_1, add__100_tests, 0, 50);
    tcase_add_loop_test(tc4_1, add__100_tests2, 0, 100);
    tcase_add_loop_test(tc4_1, add__100_tests3, 0, 100);
    tcase_add_test(tc4_1, add__degree);
    tcase_add_test(tc4_1, add_test_10);
    tcase_add_test(tc4_1, add_test_11);
    tcase_add_test(tc4_1, add_test_12);
    tcase_add_test(tc4_1, add_test_13);
    tcase_add_test(tc4_1, add_test_14);
    tcase_add_test(tc4_1, add_test_15);
    tcase_add_test(tc4_1, add_test_16);
    tcase_add_test(tc4_1, add_test_17);
    tcase_add_test(tc4_1, add_test_18);
    tcase_add_test(tc4_1, add_test_19);
    tcase_add_test(tc4_1, add_test_20);
    suite_add_tcase(s4, tc4_2);
    tcase_add_loop_test(tc4_2, sub__zero, 0, 100);
    tcase_add_test(tc4_2, sub__error_mark);
    tcase_add_test(tc4_2, sub__error_mark2);
    tcase_add_test(tc4_2, sub__error_mark3);
    tcase_add_test(tc4_2, sub__error_mark4);
    tcase_add_test(tc4_2, sub__error_mark5);
    tcase_add_loop_test(tc4_2, sub__100_tests, 0, 100);
    suite_add_tcase(s4, tc4_3);
    tcase_add_test(tc4_3, mul_test1);
    tcase_add_test(tc4_3, mul_test2);
    tcase_add_test(tc4_3, mul_test3);
    tcase_add_loop_test(tc4_3, mul__100_tests, 0, 10);
    tcase_add_loop_test(tc4_3, mul2__100_tests2, 0, 100);
    tcase_add_loop_test(tc4_3, mul2__100_tests3, 0, 100);
    tcase_add_loop_test(tc4_3, mul2__100_tests4, 0, 100);
    tcase_add_loop_test(tc4_3, mul2__100_tests5, 0, 100);
    tcase_add_test(tc4_3, mul2_tests4);
    tcase_add_test(tc4_3, mul_test6);
    tcase_add_test(tc4_3, mul_test7);
    tcase_add_test(tc4_3, mul_test8);
    tcase_add_test(tc4_3, mul_test9);
    suite_add_tcase(s4, tc4_4);
    tcase_add_loop_test(tc4_4, mod__1, 0, 100);
    tcase_add_loop_test(tc4_4, mod__2, 0, 100);
    tcase_add_loop_test(tc4_4, mod__3, 0, 100);
    tcase_add_loop_test(tc4_4, mod__4, 0, 100);
    tcase_add_test(tc4_4, mod_5);
    tcase_add_test(tc4_4, mod_6);
    tcase_add_test(tc4_4, mod_7);
    tcase_add_test(tc4_4, mod_8);
    tcase_add_test(tc4_4, mod_9);
    suite_add_tcase(s4, tc4_5);
    tcase_add_test(tc4_5, div__1);
    tcase_add_test(tc4_5, div__2);
    tcase_add_test(tc4_5, div__3);
    tcase_add_test(tc4_5, div__4);
    tcase_add_test(tc4_5, div__5);
    tcase_add_test(tc4_5, div__6);
    tcase_add_test(tc4_5, div__7);
    tcase_add_test(tc4_5, div__8);
    tcase_add_test(tc4_5, div__9);

    srunner_add_suite(sr, s2);
    srunner_add_suite(sr, s3);
    srunner_add_suite(sr, s4);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
